catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import IndexView, ProductCreateView, ProductUpdateView, BlogCreateView, \
    BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, ProductListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),
    # path('auto_info/<int:pk>/', auto_info, name='auto_info'),
    path('auto_info/<int:pk>/', cache_page(60)(ProductListView.as_view()), name='auto_info'),
    path('create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),

    path('create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, EmailConfirmView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('register/email_verify/', EmailConfirmView.as_view(), name='email_verify'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='Наименование')
    descriptions = models.TextField(**NULLABLE, verbose_name='Описание')
    photo = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price_for_one = models.IntegerField(verbose_name='Цена за штуку')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name='Наименование')
    descriptions = models.TextField(**NULLABLE, verbose_name='Описание')

    # created_at = models.CharField(max_length=250, verbose_name='Создан в')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='Slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение (превью)')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    num_version = models.IntegerField(verbose_name='Номер версии')
    name_version = models.CharField(max_length=150, verbose_name='Название версии')
    is_active = models.BooleanField(default=True, verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.name_version} ({self.num_version})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version
from config.settings import FORBIDDEN_WORDS


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'
        exclude = ('owner',)

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')

        for item in FORBIDDEN_WORDS:
            if item in cleaned_data.lower():
                raise forms.ValidationError('Используются недопустимое название')
        return cleaned_data

    def clean_descriptions(self):
        cleaned_data = self.cleaned_data.get('descriptions')

        for item in FORBIDDEN_WORDS:
            if item in cleaned_data.lower():
                raise forms.ValidationError('Используются недопустимые слова')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('name', 'photo', 'price_for_one', 'date_of_creation', 'last_modified_date', 'owner')

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView
# from pytils.translit import slugify
from django.core.mail import send_mail
from catalog.forms import ProductForm, VersionForm, ModeratorForm
from catalog.models import Product, Blog, Version
from catalog.services import get_cached_objects_for_products


# def index(request):
#     context = {
#         'object_list': Product.objects.all(),
#         'title': 'ВЫБЕРИТЕ ДЛЯ СЕБЯ',
#     }
#     return render(request, 'catalog/index.html', context)

# @login_required(login_url='users/')
class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'ВЫБЕРИТЕ ДЛЯ СЕБЯ'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = get_cached_objects_for_products()
        return context_data


# def auto_info(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object': product_item,
#         'title': f'Подробнее о {product_item.name}'
#     }
#     return render(request, 'catalog/product_list.html', context)


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['object'] = product_item
        context_data['title'] = f'Подробнее о {product_item.name}'

        context_data['category_pk'] = product_item.category.pk

        version_item = Version.objects.filter(product=product_item.pk, is_active=True).first()

        if version_item:
            context_data['active_version_number'] = version_item.num_version
            context_data['active_version_name'] = version_item.name_version
        else:
            context_data['active_version_number'] = 'отсутствует'
            context_data['active_version_name'] = '-'

        return context_data


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'

    # success_url = reverse_lazy('catalog:index')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('catalog:product_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        if self.request.user.is_staff and self.request.user.groups.filter(
                name='Модератор').exists():
            return ModeratorForm
        return ProductForm

    def test_func(self):
        _user = self.request.user
        _instance: Product = self.get_object()
        custom_perms: tuple = (
            'catalog_change.set_is_published',
            'catalog_change.set_category',
            'catalog_change.set_descriptions',
        )
        if _user.is_superuser or _user == _instance.owner:
            return True
        elif _user.groups.filter(name='Модератор') and _user.has_perms(custom_perms):
            return True
        return self.handle_no_permission()


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'image')
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content')

    # success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:blog_view', args=[self.kwargs.get('pk')])


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

catalog/templates/catalog/auto_info.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
{#                <img src="/media/{{ object.photo }}"#}
                <img src="{{ object.photo|mymedia }}"
                     alt="Card image cap">
                <div class="card-body">
                    <h5>{{ object.name }}</h5>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Цена от</h5>
                    <h3>{{ object.price_for_one }} руб.</h3>
                    <h5 class="card-title">О модели</h5>
                    <p class="card-text">{{ object.descriptions }}</p>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О нас</h4>
                    <p class="text-white">В компании работает более 6 000 человек. Мы предлагаем комплексные
                        решения, основанные на многолетнем опыте в автомобильном бизнесе и IT–технологиях, является
                        хранителем своего бренда и работает на протяжении всего жизненного цикла автомобиля: от запуска
                        новых продуктов до продаж подержанных автомобилей и послепродажного обслуживания. Автохолдинг
                        отвечает за все: от позиционирования бренда и маркетинга до логистики и управления глобальной
                        сетью, обеспечивает эффективный, хорошо финансируемый и ориентированный на клиента бизнес.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'catalog:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'catalog:blog_list' %}" class="text-white">Блог</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                            <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                            <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                     class="bi bi-car-front" viewBox="0 0 16 16">
                    <path d="M4 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0m10 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2zM4.862 4.276 3.906 6.19a.51.51 0 0 0 .497.731c.91-.073 2.35-.17 3.597-.17 1.247 0 2.688.097 3.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 10.691 4H5.309a.5.5 0 0 0-.447.276"/>
                    <path d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679c.033.161.049.325.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.807.807 0 0 0 .381-.404l.792-1.848ZM4.82 3a1.5 1.5 0 0 0-1.379.91l-.792 1.847a1.8 1.8 0 0 1-.853.904.807.807 0 0 0-.43.564L1.03 8.904a1.5 1.5 0 0 0-.03.294v.413c0 .796.62 1.448 1.408 1.484 1.555.07 3.786.155 5.592.155 1.806 0 4.037-.084 5.592-.155A1.479 1.479 0 0 0 15 9.611v-.413c0-.099-.01-.197-.03-.294l-.335-1.68a.807.807 0 0 0-.43-.563 1.807 1.807 0 0 1-.853-.904l-.792-1.848A1.5 1.5 0 0 0 11.18 3z"/>
                </svg>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
        </p>
        <p>Вся представленная на сайте информация носит информационный характер и не является публичной офертой,
            определяемой положениями ст. 437 (2) ГК РФ. Для получения подробной информации обращайтесь в наши
            автосалоны. Опубликованная на данном сайте информация может быть изменена в любое время без предварительного
            уведомления.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить статью "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'catalog:blog_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Статья {{ object.title }} ({{ object.slug }})
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.content }}
                        </p>
                    </div>
                    <div class="card-footer">
                        Просмотры: {{ object.views_count }}
                    </div>
                </div>
            </div>
            <div class="col-6">
                <img src="/media/{{ object.image }}" class="card-img-top object-fit-none" style="height:500px;"/>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'catalog:blog_create' %}">Добавить
            статью</a>
    </div>
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    {#                <img src="/media/{{ object.photo }}"#}
                    {#                     alt="Card image cap">#}
                    <div class="card-body">
                        {#                    <h5>{{ object.name }}</h5>#}
                        <p class="card-text">
                            {{ object|title }}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'catalog:blog_view' object.pk %}"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                <a href="{% url 'catalog:blog_edit' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Edit</a>
                                <a href="{% url 'catalog:blog_delete' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        {% if perms.catalog.add_product %}
            <a class="btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавить автомобиль</a>
        {% endif %}
    </div>
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img src="/media/{{ object.photo }}"
                         alt="Card image cap">
                    <div class="card-body">
                        <h5>{{ object.name }}</h5>
                        <p class="card-text">{{ object.descriptions|truncatechars:100 }}</p>
                        <span class="text-muted">{{ object.owner|default:"Владелец не указан" }}</span>
                        <h5></h5>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'catalog:auto_info' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Перейти</a>
                                {% if perms.catalog.change_product %}
                                    <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Изменить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                        <h4 class="card-title">
                            Редактирование автомобиля
                        </h4>
                    {% else %}
                        <h4 class="card-title">
                            Добавление автомобиля
                        </h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Добавление версии
                    </h4>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                {#                <img src="/media/{{ object.photo }}"#}
                <img src="{{ object.photo|mymedia }}"
                     alt="Card image cap">
                <div class="card-body">
                    <h5>{{ object.name }}</h5>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Цена от</h5>
                    <h3>{{ object.price_for_one }} руб.</h3>
                    <h5 class="card-title">О модели</h5>
                    <p class="card-text">{{ object.descriptions }}</p>
                    <p class="card-text" style="color: gray">Версия модели: {{ active_version_number }}</p>
                    <p class="card-text" style="color: gray">{{ active_version_name }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}